import Head from "next/head";
import Image from "next/image";
import Herosection from "../comps/Herosection";
import Navbar from "../comps/Navbar";
import styles from "../styles/Home.module.css";
import Employers from "../comps/Employers";
import Course from "../comps/Course";
import Contact from "../comps/Contact";
import Footer from "../comps/Footer";
import shelters from "../source/courses.json";
import { useRouter } from "next/router";
import { BsChevronCompactRight } from "react-icons/bs";
import React, { useState } from "react";
export default function courseLayout() {
  const router = useRouter();
  const query = router.query;
  const courseName = query.courseName;
  const [theIndex, setTheIndex] = useState(null);
  const [toggle, setToggle] = useState(false);
  console.log(courseName);

  const open = (index) => {
    console.log(index);
    setTheIndex(index);
    setToggle(!toggle);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Elite Academy || Course Layout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div>
        {shelters
          .filter((shelter) => {
            if (shelter.courseName === "") {
              return shelter;
            } else if (
              shelter.courseName
                ?.toLowerCase()
                .includes(courseName?.toLowerCase())
            ) {
              return shelter;
            }
          })
          .map((post, index) => (
            <div key={index}>
              <h1>{post.courseName}</h1>
              <br />
              <h1>{post.description}</h1>
              <br />
              <h1>{post.content}</h1>

              <div className="accordion">
                <div className="field">
                  <div
                    className="parent__container"
                    onClick={() => open(index)}
                  >
                    <div className="left">{post.year1 && <h1>Year 1</h1>}</div>

                    <div className="right">
                      <BsChevronCompactRight size={30} />
                    </div>
                  </div>
                  {toggle && theIndex === index && (
                    <div className={toggle ? "content" : "content hidden"}>
                      {post.year1.map((year) => (
                        <h1>{year}</h1>
                      ))}
                    </div>
                  )}
                </div>

                <div className="field">
                  <div
                    className="parent__container"
                    onClick={() => open(index)}
                  >
                    <div className="left">{post.year1 && <h1>Year 2</h1>}</div>

                    <div className="right">
                      <BsChevronCompactRight size={30} />
                    </div>
                  </div>
                  {toggle && theIndex === index && (
                    <div className={toggle ? "content" : "content hidden"}>
                      {post.year2.map((year) => (
                        <h1>{year}</h1>
                      ))}
                    </div>
                  )}
                </div>

                <div className="field">
                  <div
                    className="parent__container"
                    onClick={() => open(index)}
                  >
                    <div className="left">{post.year1 && <h1>Year 3</h1>}</div>

                    <div className="right">
                      <BsChevronCompactRight size={30} />
                    </div>
                  </div>
                  {toggle && theIndex === index && (
                    <div className={toggle ? "content" : "content hidden"}>
                      {post.year3.map((year) => (
                        <h1>{year}</h1>
                      ))}
                    </div>
                  )}
                </div>
              </div>

              <h1>Possible Careers</h1>
              {post.career.map((job, index) => (
                <h1 key={index}>{job}</h1>
              ))}
            </div>
          ))}
      </div>

      <Contact />
      <Footer />
    </div>
  );
}
