import Head from 'next/head'
import Image from 'next/image'
import Herosection from '../comps/Herosection'
import Navbar from '../comps/Navbar'
import styles from '../styles/Home.module.css'
import Employers from '../comps/Employers'
import Course from '../comps/Course'
import Contact from '../comps/Contact'
import Footer from '../comps/Footer'
import Data from '../source/courses.json'
import {useRouter} from 'next/router'
export default function courseLayout() {

    const router = useRouter();
    const query = router.query;
    console.log(query)
  return (
    <div className={styles.container}>    
      <Head>
        <title>Elite Academy || Course Layout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div>
          {Data.map(post=>{
              return(
                  <>
                   <h4>{post.courseName}</h4>
                   <br></br>
                   <p>{post.description}</p>
                   <br></br>
                   <p>{post.career}</p>
                  </>
              )
          })}

      </div>

      <Contact />
      <Footer />
    </div>
  )
}
