import Head from 'next/head'
import Image from 'next/image'
import Herosection from '../comps/Herosection'
import Navbar from '../comps/Navbar'
import styles from '../styles/Home.module.css'
import Employers from '../comps/Employers'
import Course from '../comps/Course'
import Contact from '../comps/Contact'
import Footer from '../comps/Footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Navbar />    
      <Head>
        <title>Elite Academy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Herosection />
      <Employers />
      <Course />
      <Contact />
      <Footer />
    </div>
  )
}
